openapi: 3.0.3
info:
  version: 0.1.0
  title: Kikurage Device Status API
  description: |
    Data: Device Status, User information

    Client: Mobile app, Device(M5Stack), Admin portal
servers:
  - url: 'http://localhost:8080'
tags:
  - name: DeviceStatusController
  - name: DeviceStatusGraphController
  - name: UserController
  - name: UserCultivationController
  - name: UserRecipeController
paths:
  /device/status/{deviceId}:
    get:
      tags:
        - DeviceStatusController
      summary: for mobile app
      description: Return your device latest status
      parameters:
        - in: path
          name: deviceId
          schema:
            type: integer
            format: int64
          required: true
          description: Device unique ID, which is pasted with label in M5Stack device
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeviceStatusResponse'
    put:
      tags:
        - DeviceStatusController
      summary: for M5Stack
      description: Register device latest status
      parameters:
        - in: path
          name: deviceId
          scheme:
            type: integer
            format: int64
          required: true
          description: Device unique ID, which is pasted with label in M5Stack device
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterDeviceStatusRequest'
      responses:
        '201':
          description: successful operation

  /device/status/{deviceId}/graph:
    get:
      tags:
        - DeviceStatusGraphController
      summary: for mobile app
      description: Return your latest weekly status of the device
      parameters:
        - in: path
          name: deviceId
          schema:
            type: integer
            format: int64
          required: true
          description: Device unique ID, which is pasted with label in M5Stack device
      responses:
        '200':
          description: successful operation
          content:
            application/json:
components:
  schemas:
    GetDeviceStatusResponse:
      type: object
      required:
        - temperature
        - humidity
        - status_type
      properties:
        temperature:
          type: integer
          example: 30
        humidity:
          type: integer
          example: 60
        status_type:
          type:
            $ref: '#/components/schemas/StatusType'
          example: "WET"
    StatusType:
      type: string
      enum:
        - NORMAL
        - WET
        - DRY
    RegisterDeviceStatusRequest:
      type: object
      required:
        - temperature
        - humidity
      properties:
        temperature:
          type: integer
          example: 25
        humidity:
          type: integer
          example: 70
