spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/device_status?characterEncoding=utf8
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE
  logging:
    level:
      root: INFO